// Default learning decks. Each deck is data + a render mode:
//   "lesson"    one card per night + a recall from 3 nights back (tap to reveal);
//               pinned:true shows always, else labelled "Tonight's lesson".
//   "browse"    collapsible, then browsable card by card (prev / next / tonight).
//   "accordion" a reference list — tap a title to reveal its body.
// Card shape: t=title, b=[lines]; lesson/browse also carry q/a (recall). Sections
// start collapsed. Swap this whole pack via config.js `decks` (a URL to a JSON
// array of decks in this shape, or "local:file.js" that sets window.CONTENT_DECKS).

var FRENCH = { name: "French", cards: [
  { t: "Subjonctif : volonté, nécessité, doute",
    b: ["Il faut que tu partes. (You must leave.)",
        "Je veux que vous veniez. (I want you to come.)",
        "Je doute qu'il ait raison. (I doubt he's right.)"],
    q: "Which mood follows 'il faut que', 'vouloir que', and 'douter que'?",
    a: "The subjunctive" },
  { t: "Subjonctif : conjonctions déclencheuses",
    b: ["Bien qu'il soit tard, il continue. (Although late...)",
        "Avant qu'elle (ne) parte, dis-lui. (Before she leaves...)",
        "À moins que tu ne viennes. (Unless you come.)",
        "Quoiqu'il pleuve, on sort. (Even though it's raining...)",
        "Note: that '(ne)' is expletive, not a negation."],
    q: "Name two conjunctions that trigger the subjunctive.",
    a: "Any two of: bien que, avant que, à moins que, quoique" },
  { t: "Subjonctif irrégulier : être, avoir, aller, faire",
    b: ["être → que je sois, qu'ils soient",
        "avoir → que j'aie, que nous ayons",
        "aller → que j'aille, qu'elle aille",
        "faire → que je fasse, que vous fassiez"],
    q: "What is the subjunctive of 'faire' for 'je'?",
    a: "que je fasse" },
  { t: "Subjonctif irrégulier : pouvoir, savoir, vouloir",
    b: ["pouvoir → que je puisse, qu'ils puissent",
        "savoir → que je sache, que tu saches",
        "vouloir → que je veuille, qu'ils veuillent",
        "Il faut que je puisse le faire. (I must be able to do it.)"],
    q: "What is the subjunctive stem for 'vouloir' ('que je...')?",
    a: "que je veuille" },
  { t: "Conditionnel : politesse soutenue",
    b: ["Auriez-vous l'obligeance de m'aider ? (Would you kindly...)",
        "Je souhaiterais que vous répondiez. (I'd like you to reply.)",
        "Il conviendrait de vérifier cela. (It would be advisable to check.)"],
    q: "What does 'auriez-vous l'obligeance de...' politely request?",
    a: "A favour — 'would you be so kind as to...'" },
  { t: "Si + imparfait → conditionnel présent",
    b: ["Si j'avais le temps, je viendrais. (If I had time, I'd come)",
        "Hypothesis about now/future, contrary to fact.",
        "Si-clause: imparfait; result: conditionnel présent."],
    q: "In 'Si tu étudiais, tu réussirais', what tense is each verb?",
    a: "Imparfait (si-clause); conditionnel présent (result)" },
  { t: "Si + plus-que-parfait → conditionnel passé",
    b: ["Si j'avais su, je serais venu. (If I'd known, I'd have come)",
        "Past hypothesis — describes an unreal past, often regret.",
        "Si-clause: plus-que-parfait; result: conditionnel passé."],
    q: "What does 'Si j'avais su, je serais venu' express?",
    a: "An unreal/regretted past condition" },
  { t: "Conditionnel journalistique",
    b: ["Le suspect serait en fuite. (reportedly on the run)",
        "Used for unconfirmed facts, not for hypotheses.",
        "Trois personnes auraient été blessées. (reportedly injured)"],
    q: "In news French, what does a verb like 'serait' signal?",
    a: "The fact is unconfirmed/alleged, not certain" },
  { t: "Plus-que-parfait : antériorité dans le récit",
    b: ["Quand il arriva, elle était déjà partie. (she'd already left)",
        "Marks an action completed before another past action.",
        "Main event = passé simple/composé; earlier one = p-q-parfait."],
    q: "Which tense shows an action happened before another past action?",
    a: "The plus-que-parfait" },
  { t: "Passé simple : reconnaissance (verbes réguliers)",
    b: ["Il parla, elle finit, ils vendirent.",
        "Literary past — never spoken, only written/read.",
        "Same meaning as passé composé: il a parlé = il parla."],
    q: "Which tense does 'il parla' correspond to in spoken French?",
    a: "Il a parlé (passé composé)" },
  { t: "Passé simple irrégulier : verbes fréquents",
    b: ["être → il fut / avoir → il eut",
        "faire → il fit / dire → il dit",
        "voir → il vit / venir → il vint"],
    q: "What is 'il fut' in the passé composé you already know?",
    a: "il a été" },
  { t: "Pronom relatif : dont",
    b: ["Replaces 'de + noun' in a relative clause.",
        "Le livre dont je parle. (...I'm talking about)",
        "C'est l'ami dont j'ai besoin. (...I need — avoir besoin de)"],
    q: "What preposition does 'dont' always replace?",
    a: "de" },
  { t: "Pronom relatif : lequel, laquelle, auquel, duquel",
    b: ["Prepositions + things; for people, qui is preferred.",
        "La chaise sur laquelle je suis assis. (...I'm sitting on)",
        "Le projet auquel je pense. (à+lequel, ...I'm thinking about)",
        "Le fait au sujet duquel il s'interroge. (he wonders about)"],
    q: "Which relative pronoun follows most prepositions (not 'de' alone)?",
    a: "Lequel/laquelle and its forms (auquel, duquel...)" },
  { t: "Ce qui, ce que, ce dont",
    b: ["Ce qui compte, c'est toi. (What matters is you — subject)",
        "Je ne sais pas ce qu'il veut. (...what he wants — object)",
        "Ce dont j'ai peur, c'est l'échec. (What I fear is failure.)"],
    q: "Which of ce qui / ce que / ce dont is the subject form ('what')?",
    a: "Ce qui" },
  { t: "Pronom relatif : où (temps et lieu)",
    b: ["La ville où je suis né. (the city where I was born)",
        "Le jour où elle est partie. (the day [when] she left)"],
    q: "Besides place, what else can the relative pronoun 'où' refer to?",
    a: "Time (e.g. le jour où...)" },
  { t: "Négation : ne...jamais / ne...plus",
    b: ["Je ne mange jamais de viande. (I never eat meat.)",
        "Il ne fume plus. (He no longer smokes.)"],
    q: "What's the difference between 'ne...jamais' and 'ne...plus'?",
    a: "Jamais = never; plus = no longer/not anymore" },
  { t: "Négation restrictive : ne...que",
    b: ["Je n'ai que deux euros. (I only have two euros.)",
        "Not a true negation — it means 'only', like 'seulement'."],
    q: "What does 'ne...que' mean, and is it a true negation?",
    a: "'Only' — it's restrictive, not a true negation" },
  { t: "Négation : ne...guère / ne...rien",
    b: ["Il ne travaille guère. (He hardly works.)",
        "Je ne vois rien. (I see nothing / don't see anything.)"],
    q: "What does 'ne...guère' mean?",
    a: "Hardly / barely" },
  { t: "Le 'ne' littéraire seul (sans pas)",
    b: ["Je ne sais que dire. (I don't know what to say.)",
        "With savoir, pouvoir, oser, cesser, 'ne' alone can negate.",
        "Il ne cesse de pleuvoir. (It doesn't stop raining.)"],
    q: "With which verbs can literary French drop 'pas' and keep just 'ne'?",
    a: "Savoir, pouvoir, oser, cesser (and similar)" },
  { t: "Faux amis avancés",
    b: ["Ignorer ≠ to ignore: to not know. Il ignore tout.",
        "Assister à ≠ to assist: to attend. J'ai assisté au procès.",
        "Prétendre ≠ to pretend: to claim. Il prétend être expert.",
        "Sensible ≠ sensible: sensitive. Elle est très sensible."],
    q: "What does 'il prétend être innocent' mean in English?",
    a: "He claims to be innocent (not 'pretends')" },
  { t: "Français oral : contractions courantes",
    b: ["T'as vu ça ? (= Tu as vu ça ?) — casual",
        "Chuis pas sûr. (= Je ne suis pas sûr.)",
        "J'sais pas. (= Je ne sais pas.) Ouais = oui (casual)"],
    q: "What do 'chuis' and 'j'sais pas' stand for in standard French?",
    a: "Je suis / Je ne sais pas" },
  { t: "Français oral : mots de remplissage",
    b: ["Du coup = so/as a result (overused filler)",
        "En fait = actually/basically (filler, not just 'in fact')",
        "Quoi (sentence-end) = filler, like 'you know'",
        "Bah, ça craint = ugh, that sucks/that's bad"],
    q: "What filler function does 'quoi' often serve at a sentence's end?",
    a: "A meaningless filler, roughly 'you know' / 'like'" },
  { t: "Expression : poser un lapin à qqn",
    b: ["Literally: 'to put down a rabbit on someone'.",
        "Actual meaning: to stand someone up.",
        "Il m'a posé un lapin hier soir. (He stood me up.)"],
    q: "What does 'poser un lapin à quelqu'un' mean?",
    a: "To stand someone up (miss a date, no notice)" },
  { t: "Expression : filer à l'anglaise",
    b: ["Literally: 'to flee in the English style'.",
        "Actual meaning: to sneak off without saying goodbye.",
        "Ironically, English says 'to take French leave'."],
    q: "What does 'filer à l'anglaise' mean, and what's ironic about it?",
    a: "To sneak off unnoticed — English says 'French leave'" },
  { t: "Vocabulaire littéraire soutenu",
    b: ["Jadis = long ago, in days of old",
        "Naguère = not long ago, recently (formal)",
        "Désormais = from now on, henceforth",
        "Quant à = as for, regarding"],
    q: "Which is more recent: 'jadis' or 'naguère'?",
    a: "Naguère (jadis = long ago; naguère = not long ago)" },
  { t: "Inversion après certains adverbes (écrit soutenu)",
    b: ["Peut-être viendra-t-il. (Perhaps he'll come.)",
        "Sans doute a-t-elle raison. (She's probably right.)",
        "À peine était-il arrivé qu'il partit. (He'd barely arrived...)"],
    q: "When a formal sentence starts with 'peut-être', what happens?",
    a: "Subject-verb inversion (e.g. peut-être viendra-t-il)" }
]};

// SAS Survival — parsed from John 'Lofty' Wiseman, "SAS Survival Handbook"
// (Revised Ed., HarperCollins 2009), walked in the book's own chapter order:
// Essentials, Strategy, Climate & Terrain, Food, Camp Craft, Reading the
// Signs, On the Move, Health, Survival at Sea, Rescue, Disasters. Pinned like
// French (a card a night + recall), plus prev/next nav in app.js to browse it.
var SAS = { name: "SAS Survival", cards: [
  // --- 1. ESSENTIALS ---
  { t: "Survival priorities: PLAN",
    b: ["Basic needs are Food, Fire, Shelter, Water.",
        "Use PLAN to prioritise: Protection, Location,",
        "Acquisition, Navigation. Let the climate decide the",
        "order, not habit — shelter often beats water."],
    q: "What does PLAN stand for?",
    a: "Protection, Location, Acquisition, Navigation." },
  { t: "The rule of threes",
    b: ["Roughly: 3 minutes without air, 3 days without",
        "water, 3 weeks without food. Past ~9 days without",
        "water the kidneys fail. Food is rarely the first",
        "problem — cold and wet kill far sooner."],
    q: "How long can the body last without water?",
    a: "About 3 days — kidney damage sets in past ~9." },
  { t: "The survival tin",
    b: ["A sealed tobacco tin: matches, candle, flint,",
        "magnifier, needles+thread, hooks+line, button",
        "compass, snare wire, flexible saw, tiny med kit,",
        "blades, plasters, a condom (a 1-litre water bag).",
        "Polish the lid — it becomes a signal mirror."],
    q: "Why keep the tin's lid polished?",
    a: "It doubles as a signalling mirror." },
  { t: "The survival pouch",
    b: ["A bigger back-up worn on the belt, not pocketed:",
        "fuel, food, survival bag and signalling kit packed",
        "in a mess tin that also cooks. Grab-able in an",
        "instant. Replace anything you use at once."],
    q: "What else is the pouch's mess tin for?",
    a: "Cooking — and it protects the kit packed inside." },
  { t: "The will to survive",
    b: ["Knowledge and the will to live beat any gadget.",
        "Panic and giving up kill faster than cold or",
        "hunger. Set small goals, keep busy, stay hopeful —",
        "people with the will have survived the impossible."],
    q: "What single factor most decides survival?",
    a: "The will to survive." },
  // --- 2. STRATEGY ---
  { t: "First actions after an incident",
    b: ["Get clear of fire and fuel, then treat casualties",
        "(see the first-aid order). Salvage everything",
        "usable before you move. Usually stay near the",
        "wreck: it shelters you and is easy to spot."],
    q: "Stay with the wreckage or walk out?",
    a: "Usually stay — it shelters you and is easy to find." },
  { t: "Size up before you act",
    b: ["Weigh your health, the others, your kit, the",
        "terrain, the climate and the odds of rescue, then",
        "make a plan. Don't move at night or in bad weather",
        "unless staying put is worse."],
    q: "What comes before any action?",
    a: "Sizing up: health, kit, terrain, weather, rescue." },
  // --- 3. CLIMATE & TERRAIN ---
  { t: "Siting a shelter",
    b: ["Off valley floors (cold air and floods sink there)",
        "and off ridges (wind, lightning). Away from lone or",
        "dead trees and gullies. Set the entrance side-on to",
        "the wind, near water and fuel, on dry ground."],
    q: "Why avoid valley bottoms?",
    a: "Cold air pools and flash floods run through them." },
  { t: "Cold climates: the COLD rule",
    b: ["Trapped air insulates — wear loose layers, not one",
        "thick coat, and shed them before you sweat.",
        "Keep it Clean, avoid Overheating, wear it Loose,",
        "keep it Dry. Wet and wind are the real killers."],
    q: "What does the 'COLD' rule spell out?",
    a: "Clean, avoid Overheating, Loose layers, Dry." },
  { t: "Hot climates: ration sweat",
    b: ["Work at dawn and dusk, rest shaded through the day.",
        "Keep clothes on — they slow evaporation. Salt is",
        "the first thing cut from short rations. Don't drink",
        "to 'save water' by sweating it straight out."],
    q: "'Ration sweat, not water' — how?",
    a: "Cut sweating: shade, stay covered, move when cool." },
  { t: "Finding water",
    b: ["Look downhill, at green vegetation, and where",
        "animal tracks converge. Dig at the outside of a dry",
        "riverbed's bends. Wipe heavy dawn dew with cloth",
        "for litres. A running stream beats a still pool."],
    q: "Where do you dig in a dry riverbed?",
    a: "The outside of bends, at the lowest points." },
  { t: "Water from plants",
    b: ["Tie a clear bag over a leafy, sunlit branch —",
        "transpiration drips clean water within hours.",
        "A solar still (pit, cup, sheet, weight) pulls",
        "ground moisture. Never drink sea water or urine."],
    q: "Fastest way to get water from a living tree?",
    a: "A clear bag sealed over a leafy branch in the sun." },
  // --- 4. FOOD ---
  { t: "Make water safe",
    b: ["A rolling boil for at least 1 minute kills the lot",
        "(boil longer at altitude). Filter cloudy water",
        "through cloth first. No fire? Purifying tablets, or",
        "potassium permanganate mixed to a faint pink."],
    q: "Minimum rolling boil to sterilise water?",
    a: "One minute — longer high up." },
  { t: "Food comes last",
    b: ["You have about three weeks — don't burn energy",
        "hunting on day one. Plants are the safe staple;",
        "animals cost calories to catch. Avoid fungi",
        "entirely: no field test can clear a mushroom."],
    q: "Which wild food is never worth the risk?",
    a: "Fungi — no test makes them safe in the field." },
  { t: "Plants to avoid",
    b: ["Reject: milky sap (unless known, like dandelion);",
        "a bitter-almond smell (prussic acid); a stinging or",
        "burning sap (oxalic acid); red plants; fruit in 5",
        "segments; old or wilted leaves; tiny-barbed stems."],
    q: "What does a bitter-almond smell warn of?",
    a: "Hydrocyanic (prussic) acid — discard the plant." },
  { t: "The edibility test",
    b: ["One plant part, one person. Smell it; rub juice in",
        "the elbow crook; then lips, mouth corner, tongue",
        "tip, under the tongue, chew — pausing between each.",
        "Swallow a little and WAIT 5 HOURS, eating nothing."],
    q: "How long do you wait after swallowing the test bite?",
    a: "Five hours, consuming nothing else." },
  { t: "Trap, don't hunt",
    b: ["Snares and traps work while you rest — set many.",
        "A wire noose sits on a run marked by droppings,",
        "tracks or a tunnel. Check and reset at dawn and",
        "dusk. Gut promptly and cook thoroughly."],
    q: "Why prefer snares to hunting?",
    a: "They work round the clock while you rest." },
  { t: "Fishing basics",
    b: ["Fish at dawn and dusk and after rain. Set night",
        "lines with several baited hooks and leave them.",
        "Most freshwater fish are edible — but eat them",
        "fresh; fish spoils fast. Cook if the water's doubtful."],
    q: "Best times to fish?",
    a: "Dawn, dusk, and just after rain." },
  // --- 5. CAMP CRAFT ---
  { t: "Fire: the triangle and the 3x rule",
    b: ["Fire needs heat, air and fuel — remove one and it",
        "dies. Gather tinder, kindling and fuel — three",
        "times more than you think — BEFORE you strike.",
        "Build small; a controlled fire is a safe one."],
    q: "What do you do before lighting anything?",
    a: "Gather 3x the tinder, kindling and fuel first." },
  { t: "Tinder and laying a fire",
    b: ["Tinder must catch a single spark: birch bark, char",
        "cloth, dry grass, fluff. Build a nest, add kindling",
        "as a tepee or pyramid, then fuel. Keep it off wet",
        "ground and sheltered from the wind."],
    q: "What must good tinder do?",
    a: "Catch alight from one spark." },
  { t: "Fire without matches",
    b: ["A flint or ferro rod scraped toward the nest; a 9V",
        "battery shorted across fine steel wool; a lens",
        "focusing the sun. Friction (bow-drill) is a last",
        "resort. Guard an ember once you have one."],
    q: "Two everyday items that make fire fast?",
    a: "A battery and fine steel wool." },
  { t: "Shelter types",
    b: ["Match it to climate and kit: lean-to or A-frame in",
        "woods, snow-cave or trench in snow, a shaded scrape",
        "in desert. Insulate underneath — most body heat is",
        "lost down into the cold ground."],
    q: "Where is most shelter heat lost?",
    a: "Into the ground — insulate below you." },
  { t: "One knot: the bowline",
    b: ["A fixed loop that won't slip under load yet unties",
        "easily. 'The rabbit comes out of the hole, round",
        "the tree, back down the hole.' For rescue lines,",
        "anchoring and tying off — learn this one cold."],
    q: "What is the bowline for?",
    a: "A non-slip fixed loop — rescue and anchoring." },
  { t: "Lashings and improvised tools",
    b: ["Start a lashing with a clove hitch; a square",
        "lashing joins poles at right angles. Make tools",
        "from what's around: a sharpened stick, a stone",
        "blade, a fire-hardened point."],
    q: "Which knot starts most lashings?",
    a: "The clove hitch." },
  // --- 6. READING THE SIGNS ---
  { t: "Direction by shadow stick",
    b: ["Stand a metre stick upright; mark the shadow tip,",
        "wait 15+ minutes, mark it again. The line joining",
        "the marks runs west-east — the FIRST mark is west.",
        "North-south is at right angles. Any sunny latitude."],
    q: "On the shadow-stick line, which mark is west?",
    a: "The first (earlier) shadow-tip mark." },
  { t: "Direction by watch",
    b: ["Northern hemisphere: lay the watch flat, point the",
        "hour hand at the sun; halfway between it and 12 is",
        "south. Use true local time (no daylight saving).",
        "Poor accuracy near the Equator."],
    q: "Watch method: what lies midway between hour hand and 12?",
    a: "South (in the northern hemisphere)." },
  { t: "North by the stars",
    b: ["Northern sky: follow the Plough's two 'pointer'",
        "stars about 5x their gap to Polaris, over true",
        "north. Southern sky: extend the Southern Cross's",
        "long axis about 4.5x to find due south."],
    q: "How far past the pointers is Polaris?",
    a: "About five times their spacing." },
  { t: "Reading the weather",
    b: ["Red sky at night, delight; red at morning, warning.",
        "A ring round the moon or sun means rain within a",
        "day. High wispy cirrus thickening = a front coming.",
        "Falling pressure means worsening weather."],
    q: "What does a halo round the moon suggest?",
    a: "Rain or a change within about a day." },
  // --- 7. ON THE MOVE ---
  { t: "Deciding to move",
    b: ["Move only if rescue is unlikely, you can't survive",
        "where you are, or you know the way to help. Leave",
        "clear signs of your route and heading for searchers.",
        "Travel by day and pace yourself."],
    q: "When should you leave your position?",
    a: "Only if rescue is unlikely or you can't stay put." },
  { t: "Crossing a river",
    b: ["Cross where it is wide, slow and shallow — never",
        "above rapids or a fall. Undo the pack's hip belt so",
        "you can ditch it. Face upstream, use a staff as a",
        "third leg, and shuffle. Don't cross barefoot."],
    q: "Why unbuckle the pack before wading?",
    a: "So you can shed it instantly if you go under." },
  { t: "Difficult ground",
    b: ["Keep three points of contact on rock and test each",
        "hold. Spread your weight in bog; go on all fours if",
        "it won't bear you. In snow, watch for cornices and",
        "avalanche slopes. Rest before you're spent."],
    q: "How many points of contact on rock?",
    a: "Three at all times." },
  // --- 8. HEALTH ---
  { t: "First-aid order: DR-ABC",
    b: ["Danger, Response, Airway, Breathing, Circulation,",
        "in that order. One thing jumps the queue:",
        "catastrophic bleeding — stop it with hard, direct",
        "pressure before anything else."],
    q: "What overrides the DR-ABC order?",
    a: "Catastrophic bleeding — press hard on it first." },
  { t: "Bleeding and shock",
    b: ["Firm direct pressure and elevation stop most",
        "bleeding; add dressings on top, don't peel off a",
        "soaked one. For shock: lay flat, raise the legs,",
        "keep warm, reassure, give nothing by mouth."],
    q: "Do you remove a blood-soaked dressing?",
    a: "No — press a fresh one on top of it." },
  { t: "Hypothermia",
    b: ["Watch the 'umbles': mumbles, stumbles, fumbles,",
        "grumbles — plus odd behaviour and shivering fits.",
        "Shelter, swap wet clothes for dry (head first),",
        "insulate from the ground, warm sweet drinks if",
        "conscious. No alcohol, no rubbing the limbs."],
    q: "Name the four 'umbles' of hypothermia.",
    a: "Mumbles, stumbles, fumbles, grumbles." },
  { t: "Frostbite",
    b: ["Numb, waxy-white, hard skin on fingers, toes, ears",
        "or nose. Rewarm gently with body heat or warm — not",
        "hot — water. Never rub it, never thaw if it might",
        "refreeze, and don't walk on thawed feet."],
    q: "Should you rub a frostbitten part?",
    a: "Never — rewarm it gently instead." },
  { t: "Heat illness",
    b: ["Heat exhaustion: pale, sweating, faint — rest,",
        "shade, sip water with a pinch of salt. Heatstroke:",
        "hot DRY skin, confusion, collapse — a real",
        "emergency; cool fast with water and fanning."],
    q: "Hot, dry skin with confusion means what?",
    a: "Heatstroke — cool rapidly; it's an emergency." },
  { t: "Snake bite",
    b: ["Keep the victim calm and still, bite below heart",
        "level. Put a RESTRICTING bandage above the bite —",
        "never a tourniquet — and wrap down over it. Cool",
        "the wound. NEVER cut it or try to suck out venom."],
    q: "Should you cut and suck a snake bite?",
    a: "Never — immobilise, bandage, keep the victim calm." },
  { t: "Burns",
    b: ["Cool with clean water for at least 20 minutes.",
        "Don't burst blisters or peel off stuck cloth. Cover",
        "loosely and keep it clean; sip water for shock.",
        "Deep or large burns need evacuation."],
    q: "How long do you cool a burn?",
    a: "At least 20 minutes under clean water." },
  // --- 9. SURVIVAL AT SEA ---
  { t: "Adrift at sea",
    b: ["Get everyone into the raft and out of the water —",
        "cold kills fast there. Stream the sea anchor to",
        "slow drift and steady the raft. Bail, treat",
        "casualties, and ration water from the first day."],
    q: "What steadies a life raft and slows its drift?",
    a: "The streamed sea anchor." },
  { t: "Water at sea",
    b: ["Never drink sea water — it dehydrates and maddens.",
        "Catch rain and dew; a solar still yields a little.",
        "Ration to sips. If supplies are short, expect to",
        "drink nothing for the first 24 hours."],
    q: "Can you drink sea water in extremis?",
    a: "No — it speeds death by dehydration." },
  // --- 10. RESCUE ---
  { t: "Signalling: rule of three",
    b: ["Anything in threes reads as distress: three fires",
        "in a triangle, three whistle blasts, three flashes.",
        "Prepare signals in advance and keep them ready to",
        "trigger the instant help comes into range."],
    q: "What number signals 'distress'?",
    a: "Three — of anything." },
  { t: "Whistle and mirror",
    b: ["UK mountain distress: six blasts a minute, pause,",
        "repeat — the reply is three. A mirror or polished",
        "tin flash carries for miles; sweep it across the",
        "horizon and any aircraft, even in haze."],
    q: "UK mountain distress signal on a whistle?",
    a: "Six blasts a minute; the reply is three." },
  { t: "Ground-to-air codes",
    b: ["Make symbols big (about 10 m) with colour or shadow",
        "contrast. Key ones: V = need assistance, X = need",
        "medical help, N = no, Y = yes, an arrow = heading",
        "this way. A single bar = serious injury."],
    q: "What do 'V' and 'X' signal to aircraft?",
    a: "V = need help; X = need medical help." },
  { t: "Signal fires and night signals",
    b: ["Keep signal fires laid and ready to light fast.",
        "Green leaves make white smoke, oil makes black, by",
        "day; flame shows at night. Destroy every signal",
        "once rescued so it doesn't relaunch the search."],
    q: "Why destroy your signals after rescue?",
    a: "So they don't trigger a fresh search for you." },
  // --- 11. DISASTERS ---
  { t: "If lost: STOP",
    b: ["Stop, Think, Observe, Plan. Panic walks people in",
        "circles. If anyone knows your route, staying put is",
        "usually right — a still target is far easier to",
        "find than a moving one."],
    q: "What does STOP stand for?",
    a: "Stop, Think, Observe, Plan." },
  { t: "Natural disasters",
    b: ["Flood: reach high ground; never enter moving water.",
        "Earthquake: drop, cover, hold; keep clear of glass",
        "and masonry. Wildfire: go downhill and upwind,",
        "toward already-burnt or bare ground."],
    q: "Which way do you move from a wildfire?",
    a: "Downhill and upwind, toward burnt ground." },
  { t: "Lightning and storms",
    b: ["Get off ridgelines and away from lone trees and",
        "water. Crouch low on your pack, feet together —",
        "don't lie flat. Indoors, keep off wired phones and",
        "plumbing. Thunder under 30s away means it's close."],
    q: "Safer posture caught out in a lightning storm?",
    a: "Crouch low, feet together — don't lie flat." },
  { t: "Everyday preparedness",
    b: ["Know where to shut off the water, gas and",
        "electricity at home. Keep a torch, water, food, a",
        "radio and first aid ready. In any crisis: stay",
        "calm, get information, help others, act on a plan."],
    q: "First things to locate at home for a crisis?",
    a: "The water, gas and electricity shut-offs." }
]};


var CARS = { name: "Cars", cards: [
  { t: "The four-stroke cycle",
    b: ["Suck, squeeze, bang, blow: intake pulls in fuel-air,",
        "compression squeezes it, the spark fires the power",
        "stroke, exhaust pushes out the burnt gas.",
        "Two full crank turns per cycle, per cylinder."],
    q: "The four strokes, in order?",
    a: "Intake, compression, power, exhaust — suck, squeeze, bang, blow." },
  { t: "Battery vs alternator",
    b: ["The battery only starts the car; once running, the",
        "alternator powers everything and recharges it (~14 V).",
        "Flat again after a good drive? Alternator or a drain.",
        "Flat after lights left on? Just the battery."],
    q: "What powers the car once the engine is running?",
    a: "The alternator — the battery is mainly for starting." },
  { t: "What the clutch actually is",
    b: ["A friction plate clamped between engine and gearbox.",
        "The pedal unclamps it; the biting point is partial grip.",
        "Riding the clutch or holding the bite on hills",
        "burns the plate — use the handbrake instead."],
    q: "Why does riding the clutch wear it?",
    a: "The plate slips under partial clamp — friction eats the lining." },
  { t: "Brakes: what the noises mean",
    b: ["Pads squeeze a disc; hydraulics multiply your foot.",
        "Squeal: wear indicator — pads soon.",
        "Grinding: metal on metal — pads gone, discs dying.",
        "Spongy pedal: air or old fluid in the lines."],
    q: "A grinding noise when braking means...?",
    a: "Pads worn to metal, machining the disc. Stop soon." },
  { t: "Engine oil",
    b: ["Check monthly: flat ground, engine off a few minutes,",
        "level between the dipstick marks. Top up in small pours.",
        "The red oil-pressure light means STOP the engine now —",
        "seconds matter, not miles."],
    q: "The oil light comes on while driving — what do you do?",
    a: "Pull over and kill the engine now — it runs dry in seconds." },
  { t: "Coolant and overheating",
    b: ["Never open the cap hot — it's pressurised steam.",
        "Gauge climbing? Heater on full blast pulls heat off",
        "the engine; pull over when safe.",
        "Coolant is ~50/50 antifreeze — it also stops rust."],
    q: "Cheap trick to shed engine heat in traffic?",
    a: "Heater on max — it's a second radiator into the cabin." },
  { t: "Tyres",
    b: ["Legal minimum tread: 1.6 mm — 20p test: outer band",
        "visible = too low. Check pressures monthly, cold,",
        "against the door-pillar sticker.",
        "Wear on one edge only = alignment off."],
    q: "UK minimum tread depth?",
    a: "1.6 mm across the central three-quarters of the tyre." },
  { t: "Dashboard light triage",
    b: ["Red = stop: oil pressure, temperature, battery, brakes.",
        "Amber = book it in: engine management, ABS, tyres.",
        "Flashing engine light = misfire dumping fuel —",
        "ease off and get it seen fast."],
    q: "Red vs amber warning lights?",
    a: "Red: stop now. Amber: get it checked soon." },
  { t: "Suspension",
    b: ["Springs hold the car up; dampers stop the bounce.",
        "Push a corner down hard: one rebound is right,",
        "keeps bouncing means tired dampers.",
        "Clunks over bumps: usually anti-roll-bar links or bushes."],
    q: "Car keeps bouncing after a push test — what's worn?",
    a: "The dampers (shock absorbers)." },
  { t: "How a turbo works",
    b: ["Exhaust gas spins a turbine that drives a compressor,",
        "packing more air in — more air, more fuel, more power",
        "from the same engine. Lag is the spool-up wait.",
        "Modern turbos are water-cooled; the old idle-down",
        "ritual mostly isn't needed."],
    q: "What drives a turbocharger?",
    a: "Waste exhaust gas spinning a turbine." },
  { t: "Diesels and the DPF",
    b: ["The particulate filter traps soot, then burns it off",
        "at sustained speed (regeneration).",
        "School runs never get hot enough — the filter clogs,",
        "then it's a 4-figure job. Diesels need motorway miles."],
    q: "Why do short trips kill diesel particulate filters?",
    a: "Regeneration needs a long hot run; soot builds up unburned." },
  { t: "Timing belt vs chain",
    b: ["It syncs the valves to the pistons. In most engines,",
        "a snapped belt = pistons hit valves = wrecked engine.",
        "Belts are consumables: change on schedule (~5 yrs or",
        "60-100k miles). Chains usually last the engine's life."],
    q: "What happens when a timing belt snaps?",
    a: "Valves meet pistons — usually a destroyed engine." },
  { t: "Won't start: read the symptom",
    b: ["Rapid clicking, dim lights: flat battery.",
        "One clunk, nothing: starter motor or connections.",
        "Cranks strongly but won't fire: fuel or spark.",
        "Jump leads: red to both +, black to donor -,",
        "last clamp to bare metal on the dead car."],
    q: "Cranks fine but won't fire — battery, fuel, or spark?",
    a: "Not the battery — it's fuel or spark (ignition side)." },
  { t: "Gearbox flavours",
    b: ["Manual: you clamp the clutch. Torque-converter auto:",
        "fluid coupling, smooth, slight loss.",
        "DSG: twin clutches pre-select gears — fast, complex.",
        "CVT: belt on cones, infinite ratios, droning sound."],
    q: "What makes a DSG shift so fast?",
    a: "Two clutches — the next gear is already engaged and waiting." },
  { t: "Brake fluid ages",
    b: ["It's hygroscopic — absorbs water from the air.",
        "Wet fluid boils on long descents: the pedal goes long",
        "and soft exactly when you need it most.",
        "Change every ~2 years regardless of mileage."],
    q: "Why change brake fluid that 'still works'?",
    a: "Absorbed water lowers its boiling point — fade under hard use." },
  { t: "The MOT",
    b: ["Yearly check from year 3: lights, tyres, brakes,",
        "steering, seatbelts, wipers, emissions, corrosion.",
        "Top fails are trivial: bulbs, wiper blades, tyres —",
        "walk round the car the week before."],
    q: "The most common MOT fails?",
    a: "Lights/bulbs, tyres, and wipers — all checkable at home." }
]};

// Emergency — a de-identified quick first-aid / preparedness reference deck.
// No names; conditions are named as topics, not tied to a person. NOT medical
// advice — in a real emergency call your local emergency number.
// Rendered by app.js as a collapsed section → accordion of topic titles, tap to
// reveal. Cards are reference (t + b only, no recall). Life-threat topics first.
var EMERGENCY = { name: "Emergency", cards: [
  { t: "Which number",
    b: ["999 — not breathing, unconscious, chest pain,",
        "  severe bleeding, stroke, fire, gas + symptoms.",
        "111 — urgent, not life-threatening (111.nhs.uk).",
        "105 power cut · 0800 111 999 gas · unsure → 999."] },
  { t: "CPR",
    b: ["Adult: 30 compressions (centre chest, 5–6cm,",
        "  100–120/min) : 2 breaths. Untrained = hands-only.",
        "Child/baby: 5 rescue breaths first, then 30:2,",
        "  ~1/3 depth (baby: two fingers).",
        "AED: switch on, follow the voice, pads on bare chest."] },
  { t: "Choking",
    b: ["Adult/child over 1: 5 back blows between the",
        "  shoulders, then 5 abdominal thrusts. Repeat.",
        "Baby under 1: NO abdominal thrusts — 5 back blows",
        "  (face down) then 5 chest thrusts. Repeat.",
        "Not cleared → 999. Unconscious → CPR."] },
  { t: "Anaphylaxis",
    b: ["Swollen lips/throat, wheeze, rash, faint.",
        "EpiPen → outer mid-thigh, hold firmly. Note the time.",
        "999 — say 'anaphylaxis'. Lie flat, legs up (sit up",
        "  if breathing is hard). Don't stand them up.",
        "No better in 5 min → second pen."] },
  { t: "Severe bleeding",
    b: ["Hard direct pressure; add a dressing, keep pressing;",
        "  raise the limb.",
        "Embedded object — don't pull it out, pad around it.",
        "Limb bleed won't stop → tourniquet high + tight,",
        "  note the time. 999."] },
  { t: "Seizure",
    b: ["Protect from injury, cushion the head.",
        "Do NOT restrain or put anything in the mouth.",
        "Note the start time. After: recovery position.",
        "999 if: over 5 min, first-ever, repeated, injury,",
        "  or trouble breathing."] },
  { t: "Stroke — FAST",
    b: ["Face drooping.",
        "Arm can't stay up.",
        "Speech slurred.",
        "Time — call 999 now."] },
  { t: "Head injury",
    b: ["Watch for: knocked out, repeated vomiting, seizure,",
        "  unequal pupils, clear fluid from nose/ears,",
        "  worsening drowsiness or confusion, weakness.",
        "Any of these → 999 / A&E."] },
  { t: "Burns",
    b: ["Cool under cool running water for 20 minutes.",
        "Take off jewellery/clothing unless stuck.",
        "Cover loosely with cling film.",
        "No butter, no ice, don't burst blisters.",
        "999: large/deep, face/airway, electrical, chemical."] },
  { t: "Poisoning / swallowed something",
    b: ["Do NOT make them vomit.",
        "Keep the packet or plant to show the medics.",
        "999 if drowsy or breathing badly; otherwise 111."] },
  { t: "Drowning",
    b: ["Get them out — don't put yourself in danger.",
        "5 rescue breaths FIRST, then CPR 30:2. 999."] },
  { t: "Fire — first move",
    b: ["Get out, stay out, 999 from outside.",
        "Only fight a fire smaller than a bin, with the right",
        "  extinguisher and your exit behind you. Doubt = leave.",
        "Water: wood/paper only. Foam: + liquids.",
        "CO2/powder: electrical. NEVER water on fat or electrics."] },
  { t: "Chip-pan / oil fire",
    b: ["Turn off the heat IF safe.",
        "NEVER water. NEVER move the pan.",
        "Smother: fire blanket or the pan lid",
        "  (or a wet-chemical extinguisher).",
        "Unsure → get out + 999."] },
  { t: "Electrical fire",
    b: ["Cut the power at the socket / fuse box if safe.",
        "CO2 or dry-powder extinguisher.",
        "NEVER water or foam on live electrics."] },
  { t: "Smoke & escape",
    b: ["Stay low — cleaner air is near the floor.",
        "Feel a door with the BACK of your hand first;",
        "  hot → find another way. Know two routes out.",
        "Close doors behind you. Never go back in."] },
  { t: "CO alarm",
    b: ["Everyone OUT to fresh air — don't investigate.",
        "Don't switch appliances on or off.",
        "0800 111 999 (gas emergency) or 999.",
        "Symptoms: headache, dizzy, sick, confused."] },
  { t: "Smell of gas",
    b: ["No switches on OR off. No naked flames.",
        "Open doors and windows.",
        "Turn off at the meter if you safely can. Get out.",
        "National Gas Emergency 0800 111 999."] },
  { t: "Power cut",
    b: ["Call or text 105 (free).",
        "Check neighbours / your trip switch.",
        "Keep fridge + freezer SHUT (fridge ~4h, freezer ~24h).",
        "Torches not candles; unplug sensitive gear."] },
  { t: "Water leak / burst",
    b: ["Turn off the stopcock (under the kitchen sink).",
        "Turn off water heating.",
        "Near electrics? Kill the power first.",
        "Contain it; call a plumber + insurer."] },
  { t: "Flood",
    b: ["Move up, not out into it.",
        "Never walk or drive through floodwater — 30cm of",
        "  moving water can float a car.",
        "Mains off if safe. Floodline 0345 988 1188."] },
  { t: "Go-bag (72h)",
    b: ["Water + food, meds + prescription copies,",
        "  documents (passports, insurance, med summary),",
        "  cash, chargers + power bank, torch, first aid,",
        "  kids' essentials, spare keys, warm layers.",
        "Keep it packed; both adults know where it is."] },
  { t: "Car accident",
    b: ["Stop. Engine off, hazards on, make it safe.",
        "Injuries in order: you → passengers → others.",
        "  Anyone hurt / road blocked / they flee → 999.",
        "Swap details (name, insurer, reg). Photograph all.",
        "Don't admit fault. Tell your insurer. Police within",
        "  24h if details not swapped or someone hurt (101)."] },
  { t: "Break-in",
    b: ["Intruder there now → get out / to safety, 999.",
        "  Don't confront them.",
        "Found after → don't touch anything (evidence),",
        "  101 (or 999 if they may still be near).",
        "Insurer + a crime reference number."] },
  { t: "Lost / stolen wallet or phone",
    b: ["Cards: freeze in-app, then call the bank.",
        "Phone: Find My → lock/erase; network blocks the SIM.",
        "Keys lost with ID showing the address → change locks.",
        "Stolen → 101 for a crime reference number."] }
]};

// The default deck set, in render order: {name, mode, pinned?, cards}.
window.CONTENT_DECKS = [
  { name: FRENCH.name,    mode: "lesson", pinned: true,  cards: FRENCH.cards },
  { name: SAS.name,       mode: "browse",                cards: SAS.cards },
  { name: CARS.name,      mode: "lesson", pinned: false, cards: CARS.cards },
  { name: EMERGENCY.name, mode: "accordion",             cards: EMERGENCY.cards }
];
