// Default quote pack — each entry is [ "quote", "Author, Source" ]. Rotates by day
// of the month. Swap via config.js `quotes`: a URL to JSON (this same shape) or CSV
// (text,author per row), or "local:file.js" that sets window.CONTENT_QUOTES.
window.CONTENT_QUOTES = [
  ["It is not that we have a short time to live, but that we waste a great deal of it. Life is long enough, and a sufficiently generous amount has been given to us for the highest achievements if it were all well invested.", "Seneca, On the Shortness of Life"],
  ["Have patience with everything unresolved in your heart and try to love the questions themselves, as if they were locked rooms or books written in a very foreign language. Do not now seek the answers, which cannot be given you because you would not be able to live them.", "Rilke, Letters to a Young Poet"],
  ["At dawn, when you have trouble getting out of bed, tell yourself: I have to go to work — as a human being. What do I have to complain of, if I’m going to do what I was born for — the things I was brought into the world to do? Or is this what I was created for? To huddle under the blankets and stay warm?", "Marcus Aurelius, Meditations"],
  ["In the middle of winter, I at last discovered that there was in me an invincible summer. And that makes me happy. For it says that no matter how hard the world pushes against me, within me, there’s something stronger — something better, pushing right back.", "Camus, Return to Tipasa"],
  ["Colui che sa di non avere tempo da perdere è già salvo, anche se non sa ancora come. Non è la certezza che conta, è il rifiuto di fermarsi.", "Cesare Pavese, Il mestiere di vivere"],
  ["The thing about working for yourself is that every morning you wake up unemployed. You have to earn your job all over again. That sounds terrifying, and some days it is. But it also means that every morning you wake up free.", "Paul Graham"],
  ["A man is worked upon by what he works on. He may carve out his circumstances, but his circumstances will carve him out as well. A small daily task, if it be really daily, will beat the labours of a spasmodic Hercules.", "Anthony Trollope"],
  ["The years teach much which the days never know. The individual is always mistaken. He designed many things, and drew in other persons as coadjutors, quarrelled with some or all, blundered much, and something is done; all are a little advanced, but the individual is always mistaken.", "Emerson, Experience"],
  ["Sleep is the interest we have to pay on the capital which is called in at death; and the higher the rate of interest and the more regularly it is paid, the further the date of redemption is postponed. So says Schopenhauer, but I say: sleep is the kindness the body shows the mind, reminding it gently that it is not yet infinite.", "adapted from Schopenhauer"],
  ["I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.", "Thoreau, Walden"],
  ["One must imagine Sisyphus happy. The struggle itself toward the heights is enough to fill a man’s heart.", "Camus, The Myth of Sisyphus"],
  ["We are not provided with wisdom, we must discover it for ourselves, after a journey through the wilderness which no one else can take for us, an effort which no one can spare us.", "Proust, In Search of Lost Time"],
  ["Chi vuol muovere il mondo, prima muova sé stesso. The work you do on yourself is not separate from the work you do in the world. They are the same work, done in different rooms.", "Socrates, via Plutarch"],
  ["The secret of getting ahead is getting started. The secret of getting started is breaking your complex overwhelming tasks into small manageable tasks, and then starting on the first one. And then resting. And then starting again.", "Mark Twain"],
  ["There is a vitality, a life force, an energy that is translated through you into action, and because there is only one of you in all of time, this expression is unique. And if you block it, it will never exist through any other medium and it will be lost. It is not your business to determine how good it is nor how valuable. It is your business to keep the channel open.", "Martha Graham"],
  ["Ogni mattina in Africa, una gazzella si sveglia. Sa che dovrà correre più del leone o verrà uccisa. Ogni mattina un leone si sveglia. Sa che dovrà correre più della gazzella o morirà di fame. Non importa che tu sia un leone o una gazzella: quando il sole sorge, è meglio che cominci a correre. Ma di notte, anche il leone dorme.", "proverbio africano, con aggiunta"],
  ["Put your ear down close to your soul and listen hard. The only people for me are the mad ones, the ones who are mad to live, mad to talk, mad to be saved, desirous of everything at the same time, the ones who never yawn or say a commonplace thing, but burn, burn, burn like fabulous yellow roman candles.", "Kerouac, On the Road"],
  ["You do not need to leave your room. Remain sitting at your table and listen. Do not even listen, simply wait, be quiet, still and solitary. The world will freely offer itself to you to be unmasked. It has no choice; it will roll in ecstasy at your feet.", "Kafka"],
  ["The miracle is not to walk on water. The miracle is to walk on the green earth, dwelling deeply in the present moment and feeling truly alive.", "Thich Nhat Hanh"],
  ["L’uomo è ciò che decide di essere. Non ciò che gli accade, ma ciò che sceglie di fare con ciò che gli accade. Questo è il suo privilegio, il suo fardello, e la sua libertà.", "Primo Levi, Se questo è un uomo"]
];
